spring:
  application:
    name: branch-deployer
deploy:
  password: deploy
  useRealDocker: true
  baseUrl: test.localhost
  dockerNetwork:
  deployments:
    - name: publisher-html
      filesToCopy:
        - from: ./application.properties.template
          to: /opt/boudicca-html/application.properties
      labelsToAdd:
        - key: "traefik.enable"
          value: "true"
        - key: "traefik.http.routers.branchdeployer-%CLEAN_BRANCH%.rule"
          value: "Host(`%DOMAIN%`)"
        - key: "traefik.http.routers.branchdeployer-%CLEAN_BRANCH%.entrypoints"
          value: "websecure"
        - key: "traefik.http.routers.branchdeployer-%CLEAN_BRANCH%.tls.certresolver"
          value: "myresolver"